### ISSUE TITLE
WTF? You don't have a working TeX

### ISSUE THREAD

**Issue by h0tc0d3** [periscop/cloog#41]
Why do you force people to install heavy and unnecessary package?
It really sucks!
```
Making all in .
texi2dvi -I ./doc --pdf ../../src/cloog/doc/cloog.texi -o doc/cloog.pdf
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.

For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
make[1]: *** [Makefile:2308: doc/cloog.pdf] Error 1
make: *** [Makefile:1579: all-recursive] Error 1
```

**Comment by ftynse** [comment]
Because it produces the documentation.  Generally, we find it useful 
when software comes with the documentation.

 From the little information you provided, it appears that _your_ 
installation of texi2dvi is incorrect or incomplete.  Had it been not 
installed at all, the build system would not have attempted to build the 
documentation.

If you think the build system is malfunctioning, you are welcome to 
submit a patch with a fix.  Some courteousness is also welcome if you 
want that ever reviewed.

--
Oleksandr Zinenko, PhD
Inria / École Normale Supérieure

**Comment by h0tc0d3** [comment]
LOL. The stupidest explanation that I hear! Man pages don't knowing? txt files? We are using git and github. Almost all people people using Markdown for documentation! Where I'll find you TeX under mingw? This is an illiterate decision to install the package in a few gigabytes! A competent developer always tries to limit the dependence of his package on other packages. I'm very surprised that the maintainers of such a large project do it! It's very unprofessional!

**Comment by ftynse** [comment]
Neither git nor Github are anyhow related to the our choice of 
documentation system.  Just on a side note, CLooG started _before_ 
Markdown existed and was not using git initially.  The fact that you 
don't know what TeX is or how to have it running on your system as well 
as the overall tone of the conversation lets me question your assessment 
of our professionalism ;)

Anyhow, the easy fix is to edit the Makefile produced by running 
`./configure` and replace the like looking similar to "TEXI2DVI = 
texi2dvi" to "TEXI2DVI = echo".

I will close this issue and not answer any further questions unless you 
start behaving, as you put it, "professionally".

Oleksandr Zinenko, PhD
Inria / École Normale Supérieure

**Comment by ian-bertolacci** [comment]
@ftynse I would also suggest locking.
